### ISSUE TITLE
error installing creative cloud : No package matched the SAP code 

### ISSUE THREAD

**Issue by hugo4711** [autopkg/adobe-ccp-recipes#22]
`velian-imac-11:~ nolte$ ssh admin@velian-mac-server
Last login: Sun Jun  2 20:01:44 2019 from 192.168.1.250
velian-mac-server:~ admin$ autopkg run -vv CreativeCloudApp.munki
Didn't find a recipe for CreativeCloudApp.munki.
Maybe you meant AdobeCreativeCloudInstaller.munki?
Search GitHub AutoPkg repos for a CreativeCloudApp.munki recipe? [y/n]: y

Name                                         Repo                  Path                                    
----                                         ----                  ----                                    
CreativeCloudApp.munki.recipe                adobe-ccp-recipes     Adobe/CreativeCloudApp.munki.recipe     
CreativeCloudAppNoUninstall.munki.recipe     adobe-ccp-recipes     Adobe/CreativeCloudAppNoUninstall.munki.recipe
AcrobatDC17.munki.recipe                     adobe-ccp-recipes     Adobe/examples/AcrobatDC17.munki.recipe 
AdobePhotoshopCC2017.munki.recipe            adobe-ccp-recipes     Adobe/examples/AdobePhotoshopCC2017.munki.recipe
CreativeCloudAppSerialized.munki.recipe      adobe-ccp-recipes     Adobe/CreativeCloudAppSerialized.munki.recipe
CreativeCloudAppSerialized.pkg.recipe        adobe-ccp-recipes     Adobe/CreativeCloudAppSerialized.pkg.recipe

Add recipe repo 'adobe-ccp-recipes'? [y/n]: y
Attempting git clone...

Adding /Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.adobe-ccp-recipes to RECIPE_SEARCH_DIRS...
Updated search path:
  '.'
  '~/Library/AutoPkg/Recipes'
  '/Library/AutoPkg/Recipes'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.hjuutilainen-recipes'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.arubdesu-recipes'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.dankeller-recipes'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.n8felton-recipes'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.scriptingosx-recipes'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.jessepeterson.autopkg-recipes'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.keeleysam-recipes'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.valdore86-recipes'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.facebook.Recipes-for-AutoPkg.'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.andrewvalentine-recipes'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.wardsparadox-recipes'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.chilcote-recipes'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.gerardkok-recipes'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.timsutton-recipes'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.ygini-recipes'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.hansen-m-recipes'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.jessepeterson-recipes'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.MichalMMac-recipes'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.grahamgilbert-recipes'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.bnpl-recipes'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.vmule-recipes'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.nmcspadden-recipes'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.prochat-recipes'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.jaharmi-recipes'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.swy-recipes'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.AaronBurchfield.autopkg-recipes'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.orchard-recipes'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.killahquam-recipes'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.asemak-recipes'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.jleggat-recipes'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.wholtz-recipes'
  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.adobe-ccp-recipes'

Processing CreativeCloudApp.munki...
WARNING: CreativeCloudApp.munki is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
CreativeCloudFeed
{'Input': {'ccpinfo': {
    Language = "en_US";
    Products =     (
                {
            baseVersion = "";
            sapCode = "";
            version = latest;
        }
    );
    adminPrivilegesEnabled = 1;
    appsPanelEnabled = 1;
    customerType = team;
    matchOSLanguage = 1;
    organizationName = "ADMIN_PLEASE_CHANGE";
    rumEnabled = 1;
    updatesEnabled = 0;
},
           'fetch_icon': u'false',
           'fetch_release_notes': u'false'}}
CreativeCloudFeed: No value supplied for platforms, setting default value of: osx10,osx10-64
CreativeCloudFeed: No value supplied for channels, setting default value of: ccp_hd_2,sti
CreativeCloudFeed: No value supplied for write_product_json, setting default value of: True
CreativeCloudFeed: No value supplied for parse_proxy_xml, setting default value of: False
CreativeCloudFeed: Fetching from feed URL: https://prod-rel-ffc-ccm.oobesaas.adobe.com/adobe-ffc-external/core/v4/products/all?payload=true&productType=Desktop&_type=json&channel=ccp_hd_2&channel=sti&platform=osx10&platform=osx10-64
No package matched the SAP code (), base version (), and version (latest) combination you specified.
Failed.
Receipt written to /Users/admin/Library/AutoPkg/Cache/com.github.mosen.munki.Adobe.CreativeCloudApp/receipts/CreativeCloudApp-receipt-20190605-101232.plist

The following recipes failed:
    CreativeCloudApp.munki
        Error in com.github.mosen.munki.Adobe.CreativeCloudApp: Processor: CreativeCloudFeed: Error: No package matched the SAP code (), base version (), and version (latest) combination you specified.

Nothing downloaded, packaged or imported.
`

**Comment by macmule** [comment]
You need to create an override & then change the inputs.. BUT since CC 2019 this repo barely works.

**Comment by hugo4711** [comment]
Ah ok thanks for the info
