### ISSUE TITLE
CreativeCloudApp.munki wont work

### ISSUE THREAD

**Issue by b-reich** [autopkg/adobe-ccp-recipes#24]
I got the following error when I am run
```
autopkg run CreativeCloudApp.munki
```
```
Processing CreativeCloudApp.munki...
WARNING: CreativeCloudApp.munki is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
WARNING: /Users/xaas/Library/AutoPkg/RecipeRepos/com.github.autopkg.adobe-ccp-recipes/Adobe/CreativeCloudFeed.py: No module named 'urllib2'
Failed.

The following recipes failed:
    CreativeCloudApp.munki
        Unable to import 'CreativeCloudFeed', likely due to syntax or Python error.

Nothing downloaded, packaged or imported.

```

**Comment by macmule** [comment]
Which version of AutoPkg?

You need v2 for Python 3

**Comment by b-reich** [comment]
@macmule 

```
➜  ~ autopkg version  
2.2
```
python3 is also installed

**Comment by macmule** [comment]
Ohh.. sorry I thought this was our repo.. this has one is no longer maintained.. we have https://github.com/autopkg/dataJAR-recipes/tree/master/Adobe%20CC%202019 & https://github.com/autopkg/dataJAR-recipes/tree/master/Adobe%202020

**Comment by b-reich** [comment]
@macmule is there an existing just for the adobe creative cloud app (the app which downloads photoshop etc.)

**Comment by macmule** [comment]
There's a few, folks tend to use: https://github.com/autopkg/rtrouton-recipes/blob/master/AdobeCreativeCloud/AdobeCreativeCloudInstaller.download.recipe
