### ISSUE TITLE
Package Name

### ISSUE THREAD

**Issue by csteelatgburg** [autopkg/adobe-ccp-recipes#9]
When creating the recipe override there is a value for NAME, this is used for the output of the Creative Cloud Packager. Would it be possible to set this value to include the version being created? For example, when building a Photoshop Package with base version 19 the packager would create Photoshop19.0.1.pkg.

**Comment by gregneagle** [comment]
Not without breaking other things that use NAME. (Hint -- look through all the related recipes and see where NAME is used.)  You might have better luck asking for the CreativeCloudPackager to optionally or automatically append the version to the name for the final package name.

**Comment by macmule** [comment]
@csteelatgburg which recipes are using using? .munki or .jss?

This used to be the way for .jss

**Comment by csteelatgburg** [comment]
I'm using the .pkg recipes. I can see where the .jss recipe references %version% but I'm not sure where that comes from, perhaps it is generated with the CreativeCloudVersioner runs? I also see that CreativeCloudFeed.py has version as an output, but I'm not familiar enough with how the autopkg recipes return data to know if I can just use that version in the other parts of the recipe. Meaning, can this stanza:
<dict>
                <key>Processor</key>
                <string>CreativeCloudPackager</string>
                <key>Arguments</key>
                <dict>
                    <key>package_name</key>
                    <string>%NAME%</string>
                </dict>
            </dict>

Be changed so that the package_name key is set to %NAME%%version%?
